import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gray-100 min-h-screen flex flex-col `}
        
      >
        <Header />
        <main className="flex-grow py-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
